### ISSUE TITLE
missing functionality to flatten array

### ISSUE THREAD

**Issue by MrLoh** [APIs-guru/graphql-lodash#10]
I have the following query: 

```
movie {
  cast {
    id
    role
    person {
      actorId: id
      fullName
    }
  }
}
```

Now I would like to flatten the cast into an array of not-nested objects. 

```
movie {
  cast {
    id
    role
    actorId
    fullName
  }
}
```

It seems like lodash can't do that. Would be nice to add a functionality, maybe like: 

```
movie {
  cast @_(flattenObjectDepth: 1) {
    id
    role
    person {
      actorId: id
      fullName
    }
  } 
}
```

I could create a PR, with a little help as to how transformations need to look like.

**Comment by IvanGoncharov** [comment]
@MrLoh I need to think about it and how to make it more readable.
Maybe add separate `@spread` directive, like this:
```graphql
movie {
  cast {
    id
    role
    person @spread {
      actorId: id
      fullName
    }
  } 
}
```
What do you think?

**Comment by IvanGoncharov** [comment]
@MrLoh On a second thought create separate directives for every transformation is a bad idea.
Thanks to @RomanGotsiy for explaining this to me.
Need to think a little bit more about this...

**Comment by MrLoh** [comment]
I like the spread idea, it's just a very common task in graphql I think, that's missing from lodash.

**Comment by MrLoh** [comment]
This would probably be best covered by #9 as well, maybe we should close this?

**Comment by IvanGoncharov** [comment]
@MrLoh Agree 🎉
