### ISSUE TITLE
Using graphql-lodash with Apollo mutation refetch queries ?

### ISSUE THREAD

**Issue by kavink** [APIs-guru/graphql-lodash#12]
I am trying to figure out how to make ```graphql-lodash``` work with Apollo mutation refetch queries . Thoughts ?

**Comment by IvanGoncharov** [comment]
@kavink You can read about it here: https://blog.apis.guru/query-and-transformation-collocation-with-apollo-client-and-graphql-lodash-9111448ec01b

Or in README: https://github.com/APIs-guru/graphql-lodash#usage-with-react-apollo

**Comment by kavink** [comment]
@IvanGoncharov thanks that works for queries but does not work when mutation is called , and mutation has refetchQueries

**Comment by kavink** [comment]
https://www.apollographql.com/docs/react/basics/mutations.html#graphql-mutation-options-refetchQueries

**Comment by IvanGoncharov** [comment]
@kavink Thank for the link. We personally don't use Apollo so it would be great if some Apollo expert helps us to answer this question.
PR that adds relevant info to README is very welcomed.
