### ISSUE TITLE
@_(get: "x") will remove all properties on the current object

### ISSUE THREAD

**Issue by SubZane** [APIs-guru/graphql-lodash#45]
The example below will remove id and title from the post object. Is this as intended?
```
query getPost {
  post(id: 1) @_(get:"user") {
    id
    title
    user {
      id
      name
      username
      email
    }
  }
}
```

**Comment by IvanGoncharov** [comment]
@SubZane Yes, exactly.
You should get content of `user` under the top-level `post` field.

**Comment by SubZane** [comment]
ok thanks for the reply, to bad I was hoping that the fields would merge instead of just replacing the whole post object with the user.

But I understand that would be much more problematic to do :)
